title: Journal of Agricultural Research 
ocns: [1754420, 54517086, 557659325, 606211283]
tokens: 
  :m: '(MONTH:)?(?<month>(JAN?(UARY)?|F(EB)?(RUARY)?|MA?R(CH)?|APR?(IL)?|MA?Y|J(E|UN|UNE)|J(Y|L|UL|ULY)|AU?G(UST)?|S(EP?T?)?(EMBER)?|O(CT?)?(OBER)?|N(OV)?(EMBER)?|D(EC?)?(EMBER)?)\.?)'
patterns:
  - '%r{^#{@tokens[:v]}
      \s\(?(?<year>\d{4})\)?$
      }xi'
  - '%r{^#{@tokens[:v]}
    \s\(?(?<year>\d{4})#{@tokens[:div]}
    (?<start_month>#{@tokens[:m]})#{@tokens[:div]}
    (?<end_month>#{@tokens[:m]})\s?\)?$
    }xi'
  - '%r{^#{@tokens[:v]}#{@tokens[:div]}
    \(?(?<start_month>#{@tokens[:m]})\s?-
    (?<end_month>#{@tokens[:m]})
    \s\(?(?<year>\d{4})\)?$
    }xi'
  - '%r{^V\.\s(?<volume>\d{1,2})(?<year>\d{4})#{@tokens[:div]}
    (?<start_month>#{@tokens[:m]})#{@tokens[:div]}
    (?<end_month>#{@tokens[:m]})$
    }xi'
  - '%r{^V\.\s(?<start_volume>\d{1,2})-(?<end_volume>\d{1,2})
      #{@tokens[:div]}\(?(?<year>\d{4})\)?$
     }xi'
  - '%r{^#{@tokens[:v]}#{@tokens[:div]}
    \(?(?<start_year>\d{4})#{@tokens[:div]}(?<end_year>\d{2,4})\)?
    }xi'
  - '%r{^V(?<volume>\d{1,2})\s
    (?<start_month>#{@tokens[:m]})#{@tokens[:div]}
    (?<end_month>#{@tokens[:m]})
    \((?<year>\d{4})\)$
    }xi'
  - '%r{^#{@tokens[:v]}
    (#{@tokens[:div]}#{@tokens[:y]})?
    (#{@tokens[:div]}START\sYEAR:(?<start_year>\d{4}))?
    (#{@tokens[:div]}END\sYEAR:(?<end_year>\d{4}))?
    (#{@tokens[:div]}#{@tokens[:m]})?
    (#{@tokens[:div]}START\sMONTH:(?<start_month>#{@tokens[:m]}))?
    (#{@tokens[:div]}end\smonth:(?<end_month>#{@tokens[:m]}))?
    $}xi'
t_order: [volume, year, start_year, end_year, month, start_month, end_month]
